version: '3'
services:
  web:
    build: ./zoo
    command: python3 ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres

  db:
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
