version: '3'
services:
  web:
    build: ./zoo
    ports:
    - 8000:8000
    volumes:
    - ./zoo:/data
    depends_on:
    - db
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres@db/postgres

  db:
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
