# Generated by Django 3.1.2 on 2020-10-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20201007_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careperiod',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='careperiods', to='park.animal'),
        ),
        migrations.AlterField(
            model_name='careperiod',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='careperiods', to='park.employee'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dangerous',
            field=models.BooleanField(default=False, verbose_name='Опасен для человека'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
