# Generated by Django 3.1.2 on 2020-10-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20201012_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(choices=[('Orange', 'Orange'), ('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='park.category'),
        ),
        migrations.AlterField(
            model_name='placementperiod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placementperiods', to='park.category'),
        ),
        migrations.AlterField(
            model_name='placementperiod',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placementperiods', to='park.space'),
        ),
    ]
