# Generated by Django 3.1.2 on 2020-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20201012_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careperiod',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
