# Generated by Django 3.1.2 on 2020-10-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_auto_20201017_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='space',
        ),
        migrations.AddField(
            model_name='category',
            name='flying',
            field=models.BooleanField(default=False, verbose_name='Летающий'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=15),
        ),
    ]
